name: Pull Request Notifier

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on ZEIT Now
        uses: amondnet/now-deployment@v1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
          zeit-team-id: team_XXXXXXXXXXX
          now-args: '--prod'
      - name: GitHub Action for Slack
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: ThisIsMyUsername # Optional.
          SLACK_CHANNEL: testing-stuff-out # Optional.
          SLACK_OVERRIDE_MESSAGE: "Custom message" # Optional.
        uses: Ilshidur/action-slack@1.0.1
        with:
          args: "A new commit has been pushed."
