name: Pull Request Notifier

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: deploy now
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
        run: now --no-clipboard -t ${ZEIT_TOKEN} -m commit=${GITHUB_SHA} -m branch=${GITHUB_REF}
      - uses: iam4x/now-deploy-preview-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
      - name: GitHub Action for Slack
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: ThisIsMyUsername # Optional.
          SLACK_CHANNEL: testing-stuff-out # Optional.
          SLACK_OVERRIDE_MESSAGE: "Custom message" # Optional.
        uses: Ilshidur/action-slack@1.0.1
        with:
          args: "A new commit has been pushed."
