name: Pull Request Workflow

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ESLint checks
        uses: gimenete/eslint-action@1.0
      - name: Run Jest
        uses: stefanoeb/jest-action@1.0.0
      - name: GitHub Action for Slack
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: ThisIsMyUsername # Optional.
          SLACK_CHANNEL: testing-stuff-out # Optional.
          SLACK_OVERRIDE_MESSAGE: "Custom message" # Optional.
        uses: Ilshidur/action-slack@1.0.1
        with:
          args: "A new commit has been pushed."
