name: Pull Request Workflow

on: [pull_request]

jobs:
  lovebot:
    runs-on: ubuntu-latest

    steps:
      - name: Some test action 12345
        uses: icew1nd/some-test-action-12345@v.1.0.7
        with:
          gh-token: ${{ secrets.GH_TOKEN }}
  build:
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          npm ci
          npm run build --if-present
          npm test
        env:
          CI: true
  slack:
    runs-on: ubuntu-latest

    steps:
     - name: GitHub Action for Slack
       env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: ThisIsMyUsername # Optional.
          SLACK_CHANNEL: testing-stuff-out # Optional.
          SLACK_OVERRIDE_MESSAGE: "Custom message" # Optional.
        uses: Ilshidur/action-slack@1.0.1
        with:
          args: "A new pull request has been created!"
