name: Node CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Some test action 12345
      uses: icew1nd/some-test-action-12345@v.1.0.3
      with:
        who-to-greet: 'Mona the Octocat'
